services:
  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    hostname: nginx-lb
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - inmeta
    depends_on:
      - backend-1
      - backend-2

  backend-1:
    build: .
    container_name: backend-1
    hostname: backend-1
    expose:
      - "8080"
    networks:
      - inmeta
    env_file: .env
    depends_on:
      - database

  backend-2:
    build: .
    container_name: backend-2
    hostname: backend-2
    expose:
      - "8080"
    networks:
      - inmeta
    env_file: .env
    depends_on:
      - database

  database:
    image: postgres:16.9-alpine3.22
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - inmeta
    volumes:
      - .docker/database:/var/lib/postgresql

networks:
  inmeta:
