services:
  database:
    image: postgres:16.9-alpine3.22
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - inmeta
    volumes:
      - .docker/database:/var/lib/postgresql

networks:
  inmeta:
